server {
    listen 80;
    server_name admin.yago.loc api.yago.loc;
    return 301 https://$host$request_uri;
}

upstream phpfpm {
    server admin:9000;
}

upstream apigo {
    server api:9009;
}

server {
    listen 443 ssl;
    http2 on;
    index index.php;
    server_name admin.yago.loc;
	
	ssl_certificate      /etc/nginx/ssl/yago.loc.crt;
    ssl_certificate_key  /etc/nginx/ssl/yago.loc.key;
    # Для локальної розробки вимкнено stapling
    ssl_stapling off;
    ssl_stapling_verify off;

    root /var/www/admin/public;

    # Кінцева точка Vite HMR WebSocket (перевіряється параметром запиту)
    location ~* ^/\?.*token= {
        proxy_pass http://admin:5173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location / {
        try_files $uri /index.php?$args;
    }

    # Проксі-сервер Vite dev для HMR та ресурсів
    location ~ ^/(resources/|@vite/|@vite-hmr|@id/|@fs/|node_modules/|@react-refresh) {
        proxy_pass http://admin:5173;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass phpfpm;
        fastcgi_index index.php;
        fastcgi_read_timeout 1000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location /connection/websocket {
        proxy_pass http://centrifugo:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name storage.yago.loc;

    ssl_certificate      /etc/nginx/ssl/yago.loc.crt;
    ssl_certificate_key  /etc/nginx/ssl/yago.loc.key;
    ssl_stapling off;
    ssl_stapling_verify off;

    # Проксіювання всіх запитів до MinIO
    location / {
        auth_basic off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $http_host;
        proxy_connect_timeout 300;
        proxy_read_timeout 300;
        proxy_send_timeout 300;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        chunked_transfer_encoding off;
        proxy_pass http://minio:9000/yago/;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name api.yago.loc;

	ssl_certificate      /etc/nginx/ssl/yago.loc.crt;
    ssl_certificate_key  /etc/nginx/ssl/yago.loc.key;
    # Для локальної розробки вимкнено stapling
    ssl_stapling off;
    ssl_stapling_verify off;


    location / {
        proxy_pass http://apigo;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}